# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import trillian_map_api_pb2 as trillian__map__api__pb2


class TrillianMapStub(object):
  """TrillianMap defines a service which provides access to a Verifiable Map as
  defined in the Verifiable Data Structures paper.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLeaves = channel.unary_unary(
        '/trillian.TrillianMap/GetLeaves',
        request_serializer=trillian__map__api__pb2.GetMapLeavesRequest.SerializeToString,
        response_deserializer=trillian__map__api__pb2.GetMapLeavesResponse.FromString,
        )
    self.GetLeavesByRevision = channel.unary_unary(
        '/trillian.TrillianMap/GetLeavesByRevision',
        request_serializer=trillian__map__api__pb2.GetMapLeavesByRevisionRequest.SerializeToString,
        response_deserializer=trillian__map__api__pb2.GetMapLeavesResponse.FromString,
        )
    self.SetLeaves = channel.unary_unary(
        '/trillian.TrillianMap/SetLeaves',
        request_serializer=trillian__map__api__pb2.SetMapLeavesRequest.SerializeToString,
        response_deserializer=trillian__map__api__pb2.SetMapLeavesResponse.FromString,
        )
    self.GetSignedMapRoot = channel.unary_unary(
        '/trillian.TrillianMap/GetSignedMapRoot',
        request_serializer=trillian__map__api__pb2.GetSignedMapRootRequest.SerializeToString,
        response_deserializer=trillian__map__api__pb2.GetSignedMapRootResponse.FromString,
        )
    self.GetSignedMapRootByRevision = channel.unary_unary(
        '/trillian.TrillianMap/GetSignedMapRootByRevision',
        request_serializer=trillian__map__api__pb2.GetSignedMapRootByRevisionRequest.SerializeToString,
        response_deserializer=trillian__map__api__pb2.GetSignedMapRootResponse.FromString,
        )


class TrillianMapServicer(object):
  """TrillianMap defines a service which provides access to a Verifiable Map as
  defined in the Verifiable Data Structures paper.
  """

  def GetLeaves(self, request, context):
    """GetLeaves returns an inclusion proof for each index requested.
    For indexes that do not exist, the inclusion proof will use nil for the empty leaf value.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLeavesByRevision(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLeaves(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSignedMapRoot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSignedMapRootByRevision(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrillianMapServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLeaves': grpc.unary_unary_rpc_method_handler(
          servicer.GetLeaves,
          request_deserializer=trillian__map__api__pb2.GetMapLeavesRequest.FromString,
          response_serializer=trillian__map__api__pb2.GetMapLeavesResponse.SerializeToString,
      ),
      'GetLeavesByRevision': grpc.unary_unary_rpc_method_handler(
          servicer.GetLeavesByRevision,
          request_deserializer=trillian__map__api__pb2.GetMapLeavesByRevisionRequest.FromString,
          response_serializer=trillian__map__api__pb2.GetMapLeavesResponse.SerializeToString,
      ),
      'SetLeaves': grpc.unary_unary_rpc_method_handler(
          servicer.SetLeaves,
          request_deserializer=trillian__map__api__pb2.SetMapLeavesRequest.FromString,
          response_serializer=trillian__map__api__pb2.SetMapLeavesResponse.SerializeToString,
      ),
      'GetSignedMapRoot': grpc.unary_unary_rpc_method_handler(
          servicer.GetSignedMapRoot,
          request_deserializer=trillian__map__api__pb2.GetSignedMapRootRequest.FromString,
          response_serializer=trillian__map__api__pb2.GetSignedMapRootResponse.SerializeToString,
      ),
      'GetSignedMapRootByRevision': grpc.unary_unary_rpc_method_handler(
          servicer.GetSignedMapRootByRevision,
          request_deserializer=trillian__map__api__pb2.GetSignedMapRootByRevisionRequest.FromString,
          response_serializer=trillian__map__api__pb2.GetSignedMapRootResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'trillian.TrillianMap', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
